name: Deploy Master
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn test --coverage  
        env: 
          CI: true
      - run: yarn run sonar -- -Dsonar.login=${{ secrets.SONAR_LOGIN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn workspaces run build
      - name: Run Deployments
        run: yarn workspaces run deploy
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'eu-west-1'