name: Release a tag
on: 
  push:
    tags:
      - v*

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install -g lerna
      - run: lerna bootstrap
      - run: npm test -- --coverage  
        env: 
          CI: true
      - run: lerna run build
      - name: Release the hounds!
        run: lerna run release
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'eu-west-1'